micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8081
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

hello:
  controller:
    path: "/hello"
  service:
    greeting: "Hola soy el servicio"
  config:
    greeting:
      de: "Hola soy de"
      en: "Hola soy en"